# Generated by Django 4.1.3 on 2022-11-30 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrearUsuario',
            new_name='BaseUsuario',
        ),
    ]
