# Generated by Django 4.1.3 on 2022-12-23 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
