# Generated by Django 4.1.3 on 2022-12-23 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_postimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImg',
        ),
    ]
