# Generated by Django 4.1.3 on 2022-12-23 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_postimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseUsuario',
        ),
    ]
