# Generated by Django 4.1.3 on 2022-12-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='content',
        ),
    ]
