# Generated by Django 4.1.3 on 2022-12-26 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_image_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='content',
        ),
    ]
