# Generated by Django 4.1.3 on 2022-12-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_image_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
