# Generated by Django 4.1.3 on 2022-12-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_relationships_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='user_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
