# Generated by Django 4.1.3 on 2022-12-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_perfiles_user_info_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userinfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
