# Generated by Django 4.1.3 on 2022-12-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_userinfo_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='userinfo',
            new_name='content',
        ),
    ]
