# Generated by Django 4.1.3 on 2022-12-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_userinfo_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='content',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
