# Generated by Django 4.1.3 on 2022-12-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_userinfo_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
