# Generated by Django 4.1.3 on 2022-12-31 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='content',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
