# Generated by Django 4.1.3 on 2023-01-02 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_perfiles_bio_alter_userinfo_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
