# Generated by Django 4.1.3 on 2023-01-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_perfiles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='image',
            field=models.ImageField(blank=True, default='prota.png', null=True, upload_to='media/images'),
        ),
    ]
